### ISSUE TITLE
Compare with erlv8

### ISSUE THREAD

**Issue by gleber** [chromaticbum/erlang_v8#1]
Hello

How does erlang_v8 compare with https://github.com/beamjs/erlv8 ?

I am working on implementing nodejs-compatible environment using erlv8 and beamjs at the moment. It seems that erlang_v8 and other ev8_\* projects have very similar goals. Why did you start a new wrapper around v8 instead of using erlv8?

Cheers,
Gleb

**Comment by chromaticbum** [comment]
Hey Gleb,

Ultimately this is for being able to run the less compiler and other
node-specific JS from Erlang. But in order to get there I had to implement
some rudimentary node functions, (take a look at my ev8_node project if you
are interested, very basic stuff to get the less compiler working). I was
hopeful at first that eventually I would be able to make ev8_require able
to require .node modules! But I think there is a lot of work to do here,
because there is potentially a lot of custom C++ node in these modules that
would have to be reimplemented (node operates on the assumption that you
have one V8 isolate).

To tell you the truth, I haven't looked too too closely at erlv8, but from
what I saw it uses zeromq for async message passing in conjunction with ets
tables for message id lookup, erlang_v8 uses 2 mutexes and conds to signal
the V8 thread when there is a new message for it, and that thread passes
results back to a specified pid (which I think is much much much more
lightweight). The other thing is that erlv8 does not integrate tightly with
erlang, for instance, in order to wrap an erlang function for use from
javascript land, in erlv8 I would have to do this:

Global:set_value("greeting",  erlv8_object:new([{"English", fun
(#erlv8_fun_invocation{}, []) ->

```
                       "Hello!" end}])),
```

In erlang_v8 I would simply:
ev8:set(Context, global, <<"English">>, fun({_Context, _This}, []) ->
<<"Hello!">> end).

One cool consequence of this can be seen in my ev8_require project, look in
test/require_SUITE.erl (require_erl) to see how useful this can be, you can
simply require('module.erl'), it looks for the exports, and sets them in
your exports object!

There are a total of 0 records needed by erlang_v8 to operate. Another key
difference I guess would be that erlv8 uses parameterized modules, whereas
I do not use them anywhere. Though I guess I am not opposed to them
entirely.
A goal that I have is to keep the actual NIF side of things VERY
lightweight and do as much in Erlang as possible.

Some basics:
1. Create a new VM (one thread of execution, a new V8 isolate)
Vm = ev8:new_vm().
2. Create a context
Context = ev8:new_context(Vm).

Total overhead for creating a new Vm: 1 posix thread, 1 erlang process.

All that being said, erlang_v8 is very very young and I am still not happy
with error handling, and I am not sure how I feel about the way I handle
returning wrapped and unwrapped results, for instance there are two ways to
get a value back in erlang_v8: as a wrapped object, or a native erlang
object:

[<<"hello">>, <<"there">>] = evo8:eval(Context, <<"['hello', 'there']">>).
% Here is another difference, automatically treat lists as JS arrays, and
JS arrays as erlang lists, erlv8 treats all lists as strings, I use
binaries as the erlang string equivalent
Obj = <<>> = ev8:eval(Context, <<"['hello','there']">>). % This is a
wrapped JS object, which can be used as follows:
<<"hello">> = evo8:get(Context, Obj, 0).
<<"there">> = evo8:get(Context, Obj, 1).
Fun = evo8:wrap_fun(ev8:eval(Context, <<"String.prototype.split">>),
method). % wrap a JS function as an erlang function, method means it takes
a receive (this), static means global will be used as the receiver
[<<"h">>, <<"llo">>] = Fun(Context, <<"hello">>, [<<"e">>]).

You can also put things into erlang_v8 as a native JS object or as a
wrapped erlang term as follows:
% Make a v8 external wrapper by passing in a tuple with the value you want
to wrap in it
ev8:set(Context, global, <<"someGlobalValue">>, {hello_there}). % This sets
someGlobalValue to an external in V8 wrapping the 'hello_there' atom
hello_there = evo8:get(Context, global, <<"someGlobalValue">>).

In addition to making wrapped values, I use tuples to signify special
values sometimes as well, currently there are two: struct, and date
ev8:set(Context, global, <<"someObject">>, {struct, [{<<"field1">>,
<<"field1Value">>}]}). % Equivalent to "someObject = {field1:
'field1Value'}"
ev8:set(Context, global, <<"someDate">>, {date, 23123123}). % Equivalent to
"someDate = new Date(23123123000)", note that in erlang the unit is
seconds, which is typical of erlang, whereas in JS it is automatically
converted to milliseconds for you.

You can then retrieve the objects:
<<>> = ev8:get(Context, global, <<"someObject">>). % Retrieve as a wrapped
value
{struct, [{<<"field1">>, <<"field1Value">>}]} = evo8:get(Context, global,
<<"someObject">>). % Retrieve as native erlang object
Same with date:
<<>> = ev8:get(Context, global, <<"someDate">>).
{date, 23123123} = evo8:get(Context, global, <<"someDate">>).

Overall, you will notice there is much less code in erlang_v8 than in
erlv8, I think it is operating on a simpler framework, though I believe it
offers just as much power. I'm going to be adding in a ton of documentation
in the next couple of weeks as I have reached my goal of successfully
loading the less compiler and compiling files with it (project erless)!
I'll also hopefully be rethinking error handling to see if I can come up
with something better than current.

There are also a few functionality pieces that I want to add in the future,
namely:
tain, untaint, equals, and strict_equals, and wrap (which will, for
instance, return a wrapped JS object from erlang {struct, []})

I'm also planning on adding in dialyzer specs, and have started off already
in v8nif.erl.

Good luck with your project, I think it is a great idea, ease of
development with JS combined with the power of erlang!

Sorry for being so long-winded, but I have no docs up currently so thought
you might like a quick tutorial. I have good tests too if you want to see
some more examples.
My ev8_require project may interest you also as a starting point for
implementing node with erlang_v8. Be warned, that over the next few weeks
the project could go under some changes, though I am pretty happy with it
at present so hopefully not too much.

Feel free to email me with any more questions you may have.

Sincerely,
Hollin

**Comment by chromaticbum** [comment]
I'm looking back and seeing now that erlv8 actually does couple pretty
closely with erlang function calls, I wasn't reading it correctly. And the
equivalent code would be:
ev8:set(Context, global, <<"greeting">>, {struct, [{<<"English">>, fun(_,
[]) -> <<"Hello!">> end}]}).

**Comment by chromaticbum** [comment]
Also, if you do decide to use erlang_v8 to work on this project, I would be
quite interested in helping out with it, as you can see, I have already
started out a quick little skeleton for ev8_node :)

**Comment by gleber** [comment]
Thanks for great answer!

I'll have to evaluate performance impacts of design decisions which were made by both erlang_v8 and erlv8 to choose which project to pursue. Although erlang_v8 has an advantage of active developer :)

I'll get back to this during, most probably, February and I'll report my findings. Maybe it would be possible to implement most node.js basic modules in a way that can be reused by both systems...

Cheers,
Gleb
